"""Tests for prioritizer.prioritize() against real findings, generated by
rules.evaluate() from a real captured run (see test_rules.py / WORKPLAN.md).
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from audit_agent import prioritizer

FIXTURES = Path(__file__).parent.parent / "audit_agent" / "fixtures"
FINDINGS = json.loads((FIXTURES / "sample_findings.json").read_text())


def test_prioritize_returns_only_fails():
    fix_list = prioritizer.prioritize(FINDINGS)
    assert all(item["rule_id"] in {f["rule_id"] for f in FINDINGS if f["status"] == "FAIL"} for item in fix_list)
    assert len(fix_list) == sum(1 for f in FINDINGS if f["status"] == "FAIL")


def test_priority_is_1_indexed_and_contiguous():
    fix_list = prioritizer.prioritize(FINDINGS)
    assert [item["priority"] for item in fix_list] == list(range(1, len(fix_list) + 1))


def test_sorted_by_severity_then_rule_id():
    fix_list = prioritizer.prioritize(FINDINGS)
    severities = [prioritizer.SEVERITY_ORDER[
        next(f for f in FINDINGS if f["rule_id"] == item["rule_id"])["severity_hint"]
    ] for item in fix_list]
    assert severities == sorted(severities)
    # the critical-severity empty-password finding must lead
    assert fix_list[0]["rule_id"] == "CIS-5.4.1"


def test_every_item_has_a_real_fix_command_and_evidence_ref():
    for item in prioritizer.prioritize(FINDINGS):
        assert item["fix_command"]
        assert item["evidence_ref"] == item["rule_id"]


def test_deterministic_across_repeated_calls():
    r1 = prioritizer.prioritize(FINDINGS)
    r2 = prioritizer.prioritize(FINDINGS)
    assert r1 == r2


if __name__ == "__main__":
    tests = [v for k, v in list(globals().items()) if k.startswith("test_")]
    failures = 0
    for t in tests:
        try:
            t()
            print(f"PASS  {t.__name__}")
        except AssertionError as e:
            failures += 1
            print(f"FAIL  {t.__name__}: {e}")
    print(f"\n{len(tests) - failures}/{len(tests)} passed")
    sys.exit(1 if failures else 0)
