"""Tests for rules.evaluate() against real captures (not synthetic ones) —
audit_agent/fixtures/sample_captures.json was generated by actually running
collector.run_all() against the live cis-misconfigured target.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from audit_agent import rules

FIXTURES = Path(__file__).parent.parent / "audit_agent" / "fixtures"
CAPTURES = json.loads((FIXTURES / "sample_captures.json").read_text())

# Real, observed results from running the full pipeline against the live
# cis-misconfigured container — see WORKPLAN.md §4. Every value here is
# grounded, not guessed.
EXPECTED = {
    "CIS-5.2.10": "FAIL",
    "CIS-5.2.11": "FAIL",
    "CIS-5.3.1": "FAIL",
    "CIS-6.1.2": "PASS",
    "CIS-6.1.3": "PASS",
    "CIS-6.1.10": "FAIL",
    "CIS-3.5.1": "FAIL",
    "CIS-2.2.4": "FAIL",
    "CIS-5.4.1": "FAIL",
    "CIS-5.2.9": "FAIL",
}


def test_evaluate_returns_all_10_rules_in_order():
    findings = rules.evaluate(CAPTURES)
    assert [f["rule_id"] for f in findings] == list(EXPECTED.keys())


def test_evaluate_matches_real_captured_evidence():
    findings = rules.evaluate(CAPTURES)
    by_id = {f["rule_id"]: f for f in findings}
    for rule_id, expected_status in EXPECTED.items():
        assert by_id[rule_id]["status"] == expected_status, (
            f"{rule_id}: expected {expected_status}, got {by_id[rule_id]['status']} "
            f"(evidence: {by_id[rule_id]['evidence']!r})"
        )


def test_every_finding_has_real_evidence_not_empty():
    # Grounding check (handout Part 1): every finding must carry a real
    # evidence string, never blank.
    for f in rules.evaluate(CAPTURES):
        assert f["evidence"], f"{f['rule_id']} has no evidence"


def test_deterministic_across_repeated_calls():
    # No-drift at the rules.py layer (WORKPLAN.md §5/§6).
    r1 = rules.evaluate(CAPTURES)
    r2 = rules.evaluate(CAPTURES)
    assert r1 == r2


def test_unavailable_capture_resolves_to_unknown_not_fabricated_verdict():
    captures_with_one_broken = [dict(c) for c in CAPTURES]
    for c in captures_with_one_broken:
        if c["command_id"] == "cmd_firewall":
            c["status"] = "unavailable"
            c["reason"] = "binary not found in container"
    findings = rules.evaluate(captures_with_one_broken)
    firewall_finding = next(f for f in findings if f["rule_id"] == "CIS-3.5.1")
    assert firewall_finding["status"] == "UNKNOWN"
    assert firewall_finding["evidence"] == "binary not found in container"


if __name__ == "__main__":
    tests = [v for k, v in list(globals().items()) if k.startswith("test_")]
    failures = 0
    for t in tests:
        try:
            t()
            print(f"PASS  {t.__name__}")
        except AssertionError as e:
            failures += 1
            print(f"FAIL  {t.__name__}: {e}")
    print(f"\n{len(tests) - failures}/{len(tests)} passed")
    sys.exit(1 if failures else 0)
